import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/sidebar/side-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "min-h-screen w-full flex bg-white text-black gap-1"
        )}
      >
        {/* sidebar */}
        <SideNavbar />

        {/* main page */}
        <div className="w-full p-1 pb-2">{children}</div>
      </body>
    </html>
  );
}
