// import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/sidebar/side-navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${GeistSans.className} antialiased dark:bg-gray-950`}
    >
      <body
        className={cn(
          // inter.className,
          "max-h-screen w-full flex bg-white text-black"
        )}
      >
        {/* sidebar */}
        <SideNavbar />

        {/* main page */}
        <div className="w-full px-2 pb-2">{children}</div>
      </body>
    </html>
  );
}
